### Create a new patient entity
POST localhost:4000/patients
Content-Type: application/json

{
  "name": "Ahmed Khaled",
  "email": "kafka@consumer.com",
  "address": "cairo, egypt",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###